CREATE TABLE quiz_kotenov_5_57 (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	person_id BIGINT UNSIGNED NOT NULL,
	answers JSON,
	ptsd INT,
	gsr INT,
	depression INT,
	lie_description text,
	ptsd_description text,
	gsr_description text,
	depression_description text,
	a1 INT,
	b_ INT,
	c_ INT,
	d_ INT,
	f_ INT,
	l INT,
	ag INT,
	di INT,
	b INT,
	c INT,
	d INT,
	e INT,
	f INT,
	create_at TIMESTAMP NOT NULL,
	FOREIGN KEY (person_id) REFERENCES person(id),
	PRIMARY KEY (id)
);
