CREATE TABLE quiz (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	person_id INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	answers JSON NOT NULL,
	score INTEGER NOT NULL,
	create_at TIMESTAMP NOT NULL,
	FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE INDEX idx_quiz_name ON quiz (name);
